### PR TITLE
add new resource for TOEFL Free Practice Test

### PR DESCRIPTION
**Pull request by BurnzZ**
They added this new resource a few months ago (_I think_). I have been using it to prep for my TOEFL and it's pretty great. 🎉

### CODE REVIEW

**Comment by kathgironpe** [comment]
Hello @BurnzZ! Thank you for this. If you like, I would add you as collaborator as sometimes, I have no time to go through PR's. This is what I did for other open source projects.

**Comment by BurnzZ** [comment]
Hey @kathgironpe, sure! I'm applying to GA Tech for the Fall 2020 semester so in terms of context on this repo, it should be good.

**Comment by kathgironpe** [comment]
@BurnzZ That's great! Give yourself some time to prepare. I was working in Australia while applying for GT. I studied in 2 Universities. My education was insufficient but work experience helped. So far, I can tell you that admission is the easiest part. Good luck!

**Comment by kathgironpe** [comment]
@BurnzZ I added you up as a collaborator so whatever you find useful for admission, feel free to create a PR and merge it yourself. Thank you!

**Pull request merged**
